include:
  - project: "sk8/sk8-conf/sk8-template-ci"
    ref: main
    file:
      - "/templates/.header-template.yml"
      - "/templates/.docker-template.yml"
      - "/templates/.cicd-template.yml"
      - "/templates/.footer-template.yml"

variables:
  DOCKERFILE_NAME: "Dockerfile.simple.rshiny"
  R_DOCKER_TAG: "latest"
  MISE_A_JOUR_AUTOMATIQUE: "false"
